version: '3.9'

services:
  next_test:
    build: .
    volumes:
      - .:/usr/src/app
    command: sh -c "cd my-apps && npm run dev"
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
